### ISSUE TITLE
docker-compose.yml provided in Readme doesn't work

### ISSUE THREAD

**Issue by flyingcakes85** [echo-saurav/obsidian-ai-note-suggestion#1]
Upon using the docker compose given in readme, the following error is emitted and it exits.

```
validating /home/lain/hd1/weaviate/docker-compose.yml: (root) Additional property t2v-transformers-obsidian is not allowed
```

**Comment by echo-saurav** [comment]
Can you use it from here,
https://github.com/echo-saurav/obsidian-ai-note-suggestion/blob/main/docker/compose.yml

**Comment by flyingcakes85** [comment]
Hi, that worked. Thanks!
