### ISSUE TITLE
Occassional Text Cutoff for "Show similar notes on top"

### ISSUE THREAD

**Issue by n810K** [echo-saurav/obsidian-ai-note-suggestion#2]
![image](https://github.com/echo-saurav/obsidian-ai-note-suggestion/assets/7424933/6493d5d5-c858-47b7-84f9-a5e7394da8bf)

Occassionally, when the "Show similar notes on top" setting is enabled, the text will get cut off. This same occurs even when I am in source mode. 

However, this does not occur all the time as seen here: 
![image](https://github.com/echo-saurav/obsidian-ai-note-suggestion/assets/7424933/baff6479-983e-4f86-8a2b-11abdd94722e)

This problem seems to be caused by the "Banner" plugin. After disabling it, the spacing is fixed.

**Comment by echo-saurav** [comment]
<img width="669" alt="Screenshot 2024-01-07 at 11 50 09 AM" src="https://github.com/echo-saurav/obsidian-ai-note-suggestion/assets/76121100/87c818d5-2eff-4a72-bda3-7fb65cefff6d">

i'v tested with Banner plugin , but there was no cut off, do you have any css snippets?

I have added a minimum height in the new [release](https://github.com/echo-saurav/obsidian-ai-note-suggestion/releases/tag/0.1.8) so maybe it will be fixed for you

**Comment by n810K** [comment]
Looks like the minimum height fixed the problem. Thanks!
