### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by zeitchef** [echo-saurav/obsidian-ai-note-suggestion#3]
It's not appearing in the community store or BRAT - can we get some info in the README about the best way to install?

**Comment by Lucas-Froguel** [comment]
It does work with BRAT. You just grab this repo's URL and paste it there in the plugin. I just tested and it worked.

**Comment by zeitchef** [comment]
Thanks @Lucas-Froguel - I had a closer look at BRAT and installed just fine. Thanks!
