### ISSUE TITLE
Error: GraphQL Error (Code: 422)

### ISSUE THREAD

**Issue by MahmadSharaf** [echo-saurav/obsidian-ai-note-suggestion#4]
Thank you for creating this plugin, it looks promising and will help so much in linking my notes. The best advantage that it is local

I followed the instructions to run the docker instance, and installed the plugin manually in my vault. But it is not working and it shows this error:

`Uncaught (in promise) Error: GraphQL Error (Code: 422): {"response":{"error":[{"message":"no graphql provider present, this is most likely because no schema is present. Import a schema first!"}],"status":422,"headers":{}},"request":{"query":"{Aggregate{ObsidianVectors{meta { count }}}}"}}`

**Comment by echo-saurav** [comment]
Thank you !
I have fixed this error in the new [release](https://github.com/echo-saurav/obsidian-ai-note-suggestion/releases/tag/0.1.8)
feel free open this issue if its not fixed yet

**Comment by MahmadSharaf** [comment]
I am not if it is related or not, but this error appears `POST https://localhost:3636/v1/graphql net::ERR_SSL_PROTOCOL_ERROR`
